More functions from z_actor.c
n64decomp/majora pull request #6
Opened 2020-03-05 14:54 UTC by Cleverking2003

Decompiled more functions from z_actor.c

2020-03-06 12:59 UTC, Kenix3 reviewed
Looks good to me

2020-03-10 16:54 UTC, Rozelette requested changes
Besides minor formatting, looks good!

2020-03-10 16:54 UTC, Rozelette commented on src/code/z_actor.c
> +        else {
Put the else on the same line as the closing brace.
```suggestion
        } else {
```

2020-03-10 16:54 UTC, Rozelette commented on src/code/z_actor.c
> +		//Bit 0 - don't alloc memory
Looks like some tabs got mixed in. Replace with spaces.
```suggestion
            //Bit 1 - always loaded
            if ((entry->flags & 2) == 0) {
                //Bit 0 - don't alloc memory
```

2020-03-10 16:54 UTC, Rozelette commented on src/code/z_actor.c
> +                else {
Put the else on the same line as the closing brace.
```suggestion
                } else {
```

2020-03-10 17:24 UTC, Rozelette approved these changes

2020-03-10 17:25 UTC, merged